// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68Ti1vUZksQ0pCxwNprkg3DequVeIc0s',
    appId: '1:333093168861:web:5d670b1d9a5364d6f65d34',
    messagingSenderId: '333093168861',
    projectId: 'authapp-e7022',
    authDomain: 'authapp-e7022.firebaseapp.com',
    storageBucket: 'authapp-e7022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4BEQIzJodwZiiCeMWzmkVA35jtHP_x0',
    appId: '1:333093168861:android:55a212aba10b331ff65d34',
    messagingSenderId: '333093168861',
    projectId: 'authapp-e7022',
    storageBucket: 'authapp-e7022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlHlyXc_iUPenFzO0s-mYpOz5gdt6NWY',
    appId: '1:333093168861:ios:50651087e86e2bc6f65d34',
    messagingSenderId: '333093168861',
    projectId: 'authapp-e7022',
    storageBucket: 'authapp-e7022.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWlHlyXc_iUPenFzO0s-mYpOz5gdt6NWY',
    appId: '1:333093168861:ios:50651087e86e2bc6f65d34',
    messagingSenderId: '333093168861',
    projectId: 'authapp-e7022',
    storageBucket: 'authapp-e7022.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB68Ti1vUZksQ0pCxwNprkg3DequVeIc0s',
    appId: '1:333093168861:web:efe0e83c309ab48ef65d34',
    messagingSenderId: '333093168861',
    projectId: 'authapp-e7022',
    authDomain: 'authapp-e7022.firebaseapp.com',
    storageBucket: 'authapp-e7022.firebasestorage.app',
  );
}
